[package]
name = "http-serde"
version = "2.1.1"
authors = ["Kornel <kornel@geekhood.net>"]
edition = "2021"
description = "Serde support for the http crate. (De)serialize HeaderMap, Uri, Method, StatusCode"
license = "Apache-2.0 OR MIT"
repository = "https://gitlab.com/kornelski/http-serde"
homepage = "https://lib.rs/crates/http-serde"
categories = ["encoding"]
keywords = ["http", "serde", "deserialize", "status", "url"]
readme = "README.md"

[dependencies]
serde = { version = "1.0.203" }
http = "1.1.0"
serde_bytes = "0.11.14"

[dev-dependencies]
rmp-serde = "1.3.0"
serde_json = "1.0.117"
serde_yaml = "0.9.34"
bincode = "1.3.3"
ciborium = "0.2.2"
serde = { version = "1.0.203", features = ["derive"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--generate-link-to-definition"]
